### ISSUE TITLE
Should test.sh check for pods in myproject

### ISSUE THREAD

**Issue by rdruss** [openshiftio-vertx-boosters/vertx-secured-http-booster-redhat#26]
If you run all the booster tests in succession, you end up with all the pods deployed into the same project.  I'm not sure if there is any side effect to doing this, but something to consider.  Should the script check for existing pods in the project and ask if they should be removed before deploying new ones?

**Comment by cescoffier** [comment]
Agreed, the script should clean up everything before running.

**Comment by cescoffier** [comment]
Fixed in master.
